# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ActiveRecord::Base.transaction do
  User.destroy_all
  user1 = User.create!(username: 'Harrison')
  user2 = User.create!(username: 'Ford')
  user3 = User.create!(username: 'Mark')
  user4 = User.create!(username: 'Carrie')
  user5 = User.create!(username: 'Fisher')
  user6 = User.create!(username: 'Johnny')
  user7 = User.create!(username: 'Santo')
  user8 = User.create!(username: 'Maria')
  user9 = User.create!(username: 'Carlos')
  user0 = User.create!(username: 'Frank')

  Poll.destroy_all
  poll1 = Poll.create!(title: 'Presidential Poll', user_id: user1.id)
  poll8 = Poll.create!(title: 'Holiday Poll', user_id: user1.id)
  poll7 = Poll.create!(title: 'Sports! Poll', user_id: user1.id)
  poll6 = Poll.create!(title: 'Donut Poll', user_id: user1.id)
  poll2 = Poll.create!(title: 'Consumer Poll', user_id: user2.id)
  poll9 = Poll.create!(title: 'Doughnut Poll', user_id: user2.id)
  poll3 = Poll.create!(title: 'School Poll', user_id: user3.id)
  poll4 = Poll.create!(title: 'North Poll', user_id: user4.id)
  poll5 = Poll.create!(title: 'Financial Poll', user_id: user5.id)

  Question.destroy_all
  q1 = Question.create!(text: 'Are we screwed?', poll_id: poll1.id)
  q2 = Question.create!(text: 'Arent we screwed?', poll_id: poll2.id)
  q3 = Question.create!(text: 'Aint we screwed?', poll_id: poll3.id)
  q4 = Question.create!(text: 'R we scrud?', poll_id: poll4.id)
  q5 = Question.create!(text: 'Hello?', poll_id: poll5.id)
  q6 = Question.create!(text: 'Are we?', poll_id: poll5.id)
  q7 = Question.create!(text: 'Do you like pineapple on your donuts??', poll_id: poll6.id)
  q8 = Question.create!(text: 'Favorite donut???', poll_id: poll6.id)
  q9 = Question.create!(text: 'Like sprinkles r nah??', poll_id: poll6.id)
  q10 = Question.create!(text: 'Do you beliebe in Santa??', poll_id: poll4.id)
  q11 = Question.create!(text: 'Buy now?', poll_id: poll2.id)
  q12 = Question.create!(text: 'Favorite team?', poll_id: poll7.id)
  q13 = Question.create!(text: 'How do you spell dnt?', poll_id: poll9.id)
  q14 = Question.create!(text: 'fav holday?', poll_id: poll8.id)
  q15 = Question.create!(text: 'Snow day??', poll_id: poll3.id)
  q16 = Question.create!(text: 'Favorite class?', poll_id: poll3.id)
  q17 = Question.create!(text: 'The Rock 2020!', poll_id: poll1.id)
  q18 = Question.create!(text: 'The Kid Rock 2020?', poll_id: poll1.id)

  AnswerChoice.destroy_all

  a1 = AnswerChoice.create!(text: "Yes", question_id: q1.id)
  a2 = AnswerChoice.create!(text: "No", question_id: q2.id)
  a3 = AnswerChoice.create!(text: "Maybe", question_id: q3.id)
  a4 = AnswerChoice.create!(text: "One fish", question_id: q4.id)
  a5 = AnswerChoice.create!(text: "Two fish", question_id: q5.id)
  a6 = AnswerChoice.create!(text: "Red fish", question_id: q6.id)
  a7 = AnswerChoice.create!(text: "Blue fish", question_id: q7.id)
  a8 = AnswerChoice.create!(text: "To a or not to a", question_id: q8.id)
  a9 = AnswerChoice.create!(text: "To b or not to b", question_id: q9.id)
  a10 = AnswerChoice.create!(text: "To c or not to c", question_id: q10.id)
  a11 = AnswerChoice.create!(text: "To d or not to d", question_id: q11.id)
  a12 = AnswerChoice.create!(text: "To e or not to e", question_id: q12.id)
  a13 = AnswerChoice.create!(text: "To f or not to f", question_id: q13.id)
  a14 = AnswerChoice.create!(text: "To g or not to g", question_id: q14.id)
  a15 = AnswerChoice.create!(text: "To h or not to h", question_id: q15.id)
  a16 = AnswerChoice.create!(text: "To i or not to i", question_id: q16.id)
  a17 = AnswerChoice.create!(text: "To j or not to j", question_id: q18.id)
  a18 = AnswerChoice.create!(text: "To k or not to k", question_id: q17.id)
  a19 = AnswerChoice.create!(text: "To l or not to l", question_id: q5.id)
  a20 = AnswerChoice.create!(text: "To m or not to m", question_id: q6.id)
  a21 = AnswerChoice.create!(text: "To n or not to n", question_id: q17.id)
  a22 = AnswerChoice.create!(text: "To o or not to o", question_id: q5.id)
  a23 = AnswerChoice.create!(text: "To p or not to p", question_id: q5.id)
  a24 = AnswerChoice.create!(text: "To q or not to q", question_id: q1.id)
  a25 = AnswerChoice.create!(text: "To r or not to r", question_id: q4.id)
  a26 = AnswerChoice.create!(text: "To s or not to s", question_id: q3.id)
  a27 = AnswerChoice.create!(text: "To t or not to t", question_id: q12.id)
  a28 = AnswerChoice.create!(text: "To u or not to u", question_id: q13.id)
  a29 = AnswerChoice.create!(text: "To v or not to v", question_id: q2.id)

  Response.destroy_all
  r1 = Response.create!(answer_id: a1.id, user_id: user5.id)
  r2 = Response.create!(answer_id: a2.id, user_id: user1.id)
  r3 = Response.create!(answer_id: a3.id, user_id: user6.id)
  r4 = Response.create!(answer_id: a4.id, user_id: user5.id)
  r5 = Response.create!(answer_id: a5.id, user_id: user3.id)
  r6 = Response.create!(answer_id: a6.id, user_id: user3.id)
  r7 = Response.create!(answer_id: a7.id, user_id: user4.id)
  r8 = Response.create!(answer_id: a8.id, user_id: user7.id)
  r9 = Response.create!(answer_id: a9.id, user_id: user7.id)
  r10 = Response.create!(answer_id: a10.id, user_id: user4.id)
  r11 = Response.create!(answer_id: a11.id, user_id: user3.id)
  r12 = Response.create!(answer_id: a12.id, user_id: user8.id)
  r13 = Response.create!(answer_id: a13.id, user_id: user8.id)
  r14 = Response.create!(answer_id: a14.id, user_id: user1.id)
  r15 = Response.create!(answer_id: a15.id, user_id: user8.id)
  r16 = Response.create!(answer_id: a16.id, user_id: user0.id)
  r17 = Response.create!(answer_id: a17.id, user_id: user2.id)
  r18 = Response.create!(answer_id: a18.id, user_id: user8.id)
  r19 = Response.create!(answer_id: a19.id, user_id: user5.id)
  r20 = Response.create!(answer_id: a20.id, user_id: user8.id)
  r21 = Response.create!(answer_id: a21.id, user_id: user4.id)
  r22 = Response.create!(answer_id: a22.id, user_id: user9.id)
  r23 = Response.create!(answer_id: a23.id, user_id: user9.id)
  r24 = Response.create!(answer_id: a24.id, user_id: user2.id)
  r25 = Response.create!(answer_id: a25.id, user_id: user4.id)
  r26 = Response.create!(answer_id: a26.id, user_id: user3.id)
  r27 = Response.create!(answer_id: a27.id, user_id: user6.id)
  r28 = Response.create!(answer_id: a28.id, user_id: user6.id)
  r29 = Response.create!(answer_id: a29.id, user_id: user2.id)
end

