# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e18c4dba962bd43c3be4e1f098838671f49dbefcfba7409c568667f3528f342b3c5ee6552c6b528f89717bd69305c53a5885fa3d2b4755ca32e43a6b8e444fe7

test:
  secret_key_base: a5287ab117047788c6a0cb1eb14e7b176f20ddf37e59ebb0447d81e5c750a821235bd6c2400f4cd36b3d85494779686986429bb5ca68ed85b8d210ba607fea66

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
