require 'sqlite3'
require 'singleton'
require 'active_support/inflector'

require_relative 'users'
require_relative 'questions'
require_relative 'question_follows'
require_relative 'question_likes'
require_relative 'replies'
require_relative 'mb'
require_relative 'qdb'